[package]
name = "astix-website-tera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1.19.0"
actix-web = "4.3.1"
actix-files = "0.6.2"
lazy_static = "1.4.0"
